---
spring:
  profiles: eureka1
  application:
    name: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    serviceUrl:
      defaultZone: http://eureka2:8762/eureka/

---
spring:
  profiles: eureka2
  application:
    name: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/