server:
  port: 8888
  servlet:
    context-path: /spring

#springboot的相关配置
spring:
  profiles:
    active: dev
  config:
    location: /config

#mybatis的相关配置
mybatis:
  #mybatis的配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  #mapper的配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #对象的别名位置
  type-aliases-package: org.kxw.springboot.entity
  #其他配置
  configuration:
    map-underscore-to-camel-case: true

