server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kangxiongwei/kxw-spring
          search-paths: /kxw-spring-cloud-config/config
          default-label: master
          username:
          password:

eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/