server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kangxiongwei/kxw-spring/kxw-spring-cloud-config/
          search-paths: config
          default-label: master