server:
  port: 8881
spring:
  application:
    name: cloud-config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888
eureka:
  client:
    serviceUrl:
          defaultZone: http://localhost:8761/eureka/
