#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kxw_spring_dev?characterEncoding=UTF-8&useSSL=true
    username: root
    password: kxw672015
    driver-class-name: com.mysql.cj.jdbc.Driver
